=== cmusv-sc/PlayGenerator/input-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="entity">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="property" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute type="xs:string" name="name"/>
                                <xs:attribute name="type">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="String"/>
                                            <xs:enumeration value="int"/>
                                            <xs:enumeration value="long"/>
                                            <xs:enumeration value="Date"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="class"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cmusv-sc/PlayGenerator/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<entity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="input-schema.xsd" class="BugReport">
	<property name="title" type="String"/>
	<property name="email" type="String"/>
	<property name="name" type="String"/>
	<property name="description" type="String"/>
	<property name="organization" type="String"/>
	<property name="solved" type="int"/>
	<property name="creationDate" type="Date"/>
	<property name="updateDate" type="Date"/>	
</entity>
